convenios_app/descargas/routes.py
from flask import Blueprint, send_file, make_response
from numpy import dtype
from convenios_app.models import (BitacoraAnalista, BitacoraTarea, Convenio, TrayectoriaEquipo, TrayectoriaEtapa,
                                  RecepcionConvenio, WSConvenio,
                                  SdInvolucrada, Equipo, EntregaConvenio)
from convenios_app import db
from sqlalchemy import and_, or_
from convenios_app.bitacoras.utils import dias_habiles, obtener_iniciales
from convenios_app.informes.utils import obtener_etapa_actual_dias
from convenios_app.main.utils import generar_nombre_convenio
from convenios_app.descargas.utils import (contar_adendum, contar_convenios, contar_otros, contar_por_firmar)
from datetime import datetime, date
import pandas as pd
from io import BytesIO

MESES_LARGO = {'1': 'Enero',
               '2': 'Febrero',
               '3': 'Marzo',
               '4': 'Abril',
               '5': 'Mayo',
               '6': 'Junio',
               '7': 'Julio',
               '8': 'Agosto',
               '9': 'Septiembre',
               '10': 'Octubre',
               '11': 'Noviembre',
               '12': 'Diciembre'}

descargas = Blueprint('descargas', __name__)


@descargas.route('/descargar_informes_proceso')
def descargar_informes_proceso():
    # Obtener convenios en proceso
    convenios_query = Convenio.query.filter(Convenio.estado == 'En proceso').all()

    # Crear data frame con la tabla a descargar
    convenios_df = pd.DataFrame({
        'Institución': pd.Series(dtype='str'),
        'Convenio': pd.Series(dtype='str'),
        'Días en proceso': pd.Series(dtype='int'),
        'Etapa actual': pd.Series(dtype='str'),
        'Días en etapa': pd.Series(dtype='int'),
        'Área 1': pd.Series(dtype='str'),
        'Días A1': pd.Series(dtype='int'),
        'Área 2': pd.Series(dtype='str'),
        'Días A2': pd.Series(dtype='int'),
        'Área 3': pd.Series(dtype='str'),
        'Días A3': pd.Series(dtype='int'),
        'Área 4': pd.Series(dtype='str'),
        'Días A4': pd.Series(dtype='int')
    })

    # Recorrer convenios en proceso
    for convenio in convenios_query:
        # Crear diccionario con fila a insertar
        fila = {
            'Institución': convenio.institucion.sigla,
            'Convenio': (lambda tipo: convenio.nombre if tipo == 'Convenio' else f'(Ad) {convenio.nombre}')(
                convenio.tipo)
        }

        # Obtener días en proceso
        dias_en_proceso = 0
        for etapa in TrayectoriaEtapa.query.filter(TrayectoriaEtapa.id_convenio == convenio.id).order_by(
                TrayectoriaEtapa.ingreso.asc()).all():
            salida_etapa = (lambda salida: salida if salida != None else date.today())(etapa.salida)
            dias_en_proceso += dias_habiles(etapa.ingreso, salida_etapa)
        fila['Días en proceso'] = dias_en_proceso

        # Obtener etapa actual
        etapa_query = TrayectoriaEtapa.query.filter(and_(TrayectoriaEtapa.id_convenio == convenio.id,
                                                         TrayectoriaEtapa.salida == None)).first()
        fila['Etapa actual'] = etapa_query.etapa.etapa
        fila['Días en etapa'] = dias_habiles(etapa_query.ingreso, date.today())

        # Obtener áreas
        equipos_query = TrayectoriaEquipo.query.filter(and_(TrayectoriaEquipo.id_convenio == convenio.id,
                                                            TrayectoriaEquipo.salida == None)).all()
        if len(equipos_query) == 1:
            fila['Área 1'] = equipos_query[0].equipo.sigla
            fila['Días A1'] = dias_habiles(equipos_query[0].ingreso, date.today())
        elif len(equipos_query) == 2:
            fila['Área 1'] = equipos_query[0].equipo.sigla
            fila['Días A1'] = dias_habiles(equipos_query[0].ingreso, date.today())
            fila['Área 2'] = equipos_query[1].equipo.sigla
            fila['Días A2'] = dias_habiles(equipos_query[1].ingreso, date.today())
        elif len(equipos_query) == 3:
            fila['Área 1'] = equipos_query[0].equipo.sigla
            fila['Días A1'] = dias_habiles(equipos_query[0].ingreso, date.today())
            fila['Área 2'] = equipos_query[1].equipo.sigla
            fila['Días A2'] = dias_habiles(equipos_query[1].ingreso, date.today())
            fila['Área 3'] = equipos_query[2].equipo.sigla
            fila['Días A3'] = dias_habiles(equipos_query[2].ingreso, date.today())
        elif len(equipos_query) == 4:
            fila['Área 1'] = equipos_query[0].equipo.sigla
            fila['Días A1'] = dias_habiles(equipos_query[0].ingreso, date.today())
            fila['Área 2'] = equipos_query[1].equipo.sigla
            fila['Días A2'] = dias_habiles(equipos_query[1].ingreso, date.today())
            fila['Área 3'] = equipos_query[2].equipo.sigla
            fila['Días A3'] = dias_habiles(equipos_query[2].ingreso, date.today())
            fila['Área 4'] = equipos_query[3].equipo.sigla
            fila['Días A4'] = dias_habiles(equipos_query[3].ingreso, date.today())

        # Agregar fila
        convenios_df = pd.concat([convenios_df, pd.DataFrame([fila])], ignore_index=True)
    # Convertir números a int
    convenios_df = convenios_df.convert_dtypes()
    # Ordenar tabla
    convenios_df.sort_values(by='Institución', ignore_index=True, inplace=True)
    # Índice desde 1
    convenios_df.index += 1
    # Convertir a Excel
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    convenios_df.reset_index().to_excel(excel_writer=writer, sheet_name='Convenios en proceso', startrow=2, index=False)
    # Escribir texto en la primera fila
    workbook = writer.book
    worksheet = writer.sheets['Convenios en proceso']
    texto = f"Nota: Información extraída  del Sistema de Convenios el {datetime.today().strftime('%d-%m-%Y a las %H:%M')} - Área de Información Estadística y Tributaria, SDGEET."
    bold = workbook.add_format({'bold': True})
    worksheet.write(0, 0, texto, bold)
    # Formato de tabla
    worksheet.add_table(f'A3:N{len(convenios_df.index) + 3}', {'style': 'Table Style Medium 1',
                                                               'autofilter': False,
                                                               'columns': [{'header': '#'},
                                                                           {'header': 'Institución'},
                                                                           {'header': 'Convenio'},
                                                                           {'header': 'Días en proceso'},
                                                                           {'header': 'Etapa actual'},
                                                                           {'header': 'Días en etapa'},
                                                                           {'header': 'Área 1'},
                                                                           {'header': 'Días A1'},
                                                                           {'header': 'Área 2'},
                                                                           {'header': 'Días A2'},
                                                                           {'header': 'Área 3'},
                                                                           {'header': 'Días A3'},
                                                                           {'header': 'Área 4'},
                                                                           {'header': 'Días A4'}
                                                                           ]})

    # Guardar
    writer.save()
    # Enviar archivo para descarga
    response = make_response(output.getvalue())
    response.headers["Content-Disposition"] = f"attachment; filename=convenios_en_proceso_{date.today()}.xlsx"
    response.headers["Content-type"] = "application/x-xls"

    return response


@descargas.route('/descagar_informes_produccion')
def descargar_informes_produccion():
    # Obtener convenios en producción
    convenios_query = Convenio.query.filter(Convenio.estado == 'En producción').all()

    # Crear data frame con la tabla a descargar
    convenios_df = pd.DataFrame({
        'Institución': pd.Series(dtype='str'),
        'Convenio': pd.Series(dtype='str'),
        'Fecha firma': pd.Series(dtype='datetime64[ns]'),
        'Nro Resolución': pd.Series(dtype='int'),
        'Fecha Resolución': pd.Series(dtype='datetime64[ns]')
    })

    # Recorrer convenios en producción
    for convenio in convenios_query:
        # Crear diccionario con fila a insertar
        fila = {
            'Institución': convenio.institucion.sigla,
            'Convenio': (lambda tipo: convenio.nombre if tipo == 'Convenio' else f'(Ad) {convenio.nombre}')(
                convenio.tipo),
            'Fecha firma': convenio.fecha_documento,
            'Nro Resolución': convenio.nro_resolucion,
            'Fecha Resolución': convenio.fecha_resolucion
        }
        # Agregar fila
        convenios_df = pd.concat([convenios_df, pd.DataFrame([fila])], ignore_index=True)

    # Ordenar tabla
    convenios_df.sort_values(by='Institución', ignore_index=True, inplace=True)
    # Índice desde 1
    convenios_df.index += 1
    # Convertir a Excel
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    convenios_df.reset_index().to_excel(excel_writer=writer, sheet_name='Convenios en producción', startrow=2,
                                        index=False)
    # Escribir texto en la primera fila
    workbook = writer.book
    worksheet = writer.sheets['Convenios en producción']
    texto = f'Nota: Información extraída del Sistema de Convenios el {datetime.today().strftime("%d-%m-%Y a las %H:%M")} - Área de Información Estadística y Tributaria, SDGEET.'
    bold = workbook.add_format({'bold': True})
    worksheet.write(0, 0, texto, bold)
    # Formato de tabla

convenios_app/templates/informes/convenios_en_proceso.html
{% extends 'layout.html' %}
{% block content %}
{{ JSGlue.include() }}
<script src='{{ url_for("static", filename="script.js") }}'></script>
<script type="text/javascript">
  changeActive('#conveniosProceso')
</script>

<div class="content-section mx-2">
  <!-- Select Convenio -->
  <select autofocus class="form-control form-control-lg form-select mb-5" id="convenio">
    {% for convenio in convenios_select %}
      <option value="{{ convenio[0] }}">{{ convenio[1] }}</option>
    {% endfor %}
  </select>

  <!-- Convenios en números -->
  <div class="row text-center mb-3">
    <div class="col-lg-4">
      <h1>{{ cuenta_convenios.proceso }} <i class="fa-solid fa-comments fa-fw fa-sm"></i></h1>
      Convenios en proceso
    </div>
    <div class="col-lg-4">
      <h1>{{ cuenta_convenios.firmados }} <i class="fa-solid fa-file-signature fa-fw fa-sm"></i></h1>
      Convenios firmados
    </div>
    <div class="col-lg-4">
      <h1>{{ cuenta_convenios.publicados }} <i class="fa-solid fa-certificate fa-fw fa-sm"></i></h1>
      Convenios publicados
    </div>
  </div>


  <!-- Estadísticas e indicadores del proceso -->
  <legend class="border-bottom mb-0">Estadísticas de convenios en proceso</legend>
  <small class="mb-5">Estos datos se calculan con la información de convenios
  que ingresaron a partir del 01 de enero del 2020.</small>
  <!-- Información de días -->
  <div class="row my-3" align='center'>
    <!-- Días en proceso -->
    <p class="mb-1"><strong>Días promedio en proceso</strong></p>
    <h2><i class="fas fa-stopwatch fa-lg"></i> {{ dias_proceso }}</h2>
  </div>

  <div class="row mb-1">
    <!-- Días por etapa -->
    <div class="col-lg-6">
      <div id="chartDiasEtapas"></div>
    </div>
    <!-- Días por equipo -->
    <div class="col-lg-6">
      <div id="chartDiasEquipos"></div>
    </div>
  </div>
  <!-- Tareas por área y tiempo de respuesta -->
  <div class='row'>
    <div id='chartTareas'></div>
  </div>



<!-- Listado convenios en producción -->
<legend class='border-bottom mb-2'>Listado convenios en proceso <a class="simple-link push-right pe-1" href="{{ url_for('descargas.descargar_informes_proceso') }}"><i class="fa-solid fa-file-excel"></i></a></legend>
<div  class="mb-5 scroll" style="height: 700px;">
  <div id='listadoConvenios'></div>
</div>

</div>


<!-- Estadíticas -->
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart(){
    // Días por etapas
    // Tablas de datos según selección
    var dataEtapasTotal = google.visualization.arrayToDataTable({{ dias_etapas.total | tojson }});
    var dataEtapasDefinicion = google.visualization.arrayToDataTable({{ dias_etapas.definicion | tojson }});
    var dataEtapasConfeccion = google.visualization.arrayToDataTable({{ dias_etapas.confeccion | tojson }});
    var dataEtapasFirmas = google.visualization.arrayToDataTable({{ dias_etapas.firmas | tojson }});
    var dataEtapasResolucion = google.visualization.arrayToDataTable({{ dias_etapas.resolucion | tojson }});
    var optionsEtapas = {
      title: 'Días promedio por etapa',
      pieHole: 0.5,
      width: 500,
      height: 400,
      chartArea: {left: 10, width: '80%'},
      legend: {position: 'right', textStyle: {color: 'black', fontSize: 12}},
      titleTextStyle:{fontSize:16},
      slices: {
        0: {color: '#DFF6FF', textStyle:{color: '#051367'}, offset: 0.01},
        1: {color: '#5D8BF4', offset: 0.01},
        2: {color: '#2D31FA', offset: 0.01},
        3: {color: '#051367', offset: 0.01}
        },
      }

    // Crear gráfico Días por etapa Total
    var chartDiasEtapas = new google.visualization.PieChart(document.getElementById('chartDiasEtapas'));
    chartDiasEtapas.draw(dataEtapasTotal, optionsEtapas);

    // Días por Equipo
    // Tabla de datos según selección
    datosEquipos = [{{ dias_equipos.total | tojson }},
                    {{ dias_equipos.definicion | tojson }},
                    {{ dias_equipos.confeccion | tojson }},
                    {{ dias_equipos.firmas | tojson }},
                    {{ dias_equipos.resolucion | tojson }}
                    ];
    datosEquipos.forEach((item, i) => {
      item[0].push({role: 'style'});
    });

    var dataEquiposTotal = google.visualization.arrayToDataTable(datosEquipos[0]);
    var dataEquiposDefinicion = google.visualization.arrayToDataTable(datosEquipos[1]);
    var dataEquiposConfeccion = google.visualization.arrayToDataTable(datosEquipos[2]);
    var dataEquiposFirmas = google.visualization.arrayToDataTable(datosEquipos[3]);
    var dataEquiposResolucion = google.visualization.arrayToDataTable(datosEquipos[4]);
    var optionsEquipos = {
      title: 'Días promedio por área',
      width: 480,
      height: 400,
      chartArea: {left: 100, width: '100%'},
      legend: {position: 'right', textStyle: {color: 'black', fontSize: 12}},
      titleTextStyle:{fontSize:16},
    };

    var chartDiasEquipos = new google.visualization.BarChart(document.getElementById('chartDiasEquipos'));
    chartDiasEquipos.draw(dataEquiposTotal, optionsEquipos);

    // Tareas por área y tiempo de respuesta
    var dataTareasTotal = google.visualization.arrayToDataTable({{ tareas_equipos.total.datos | tojson}});
    var dataTareasDefinicion = google.visualization.arrayToDataTable({{ tareas_equipos.definicion.datos | tojson }});
    var dataTareasConfeccion = google.visualization.arrayToDataTable({{ tareas_equipos.confeccion.datos | tojson}});
    var dataTareasFirmas = google.visualization.arrayToDataTable({{ tareas_equipos.firmas.datos | tojson }});
    var dataTareasResolucion = google.visualization.arrayToDataTable({{ tareas_equipos.resolucion.datos | tojson }});
    var optionsTareas = {
      title : 'Tareas por área vs tiempo de respuesta promedio',
      seriesType: 'bars',
      series: {},
      isStacked: true,
      legend: { position: 'none'},
      height: 400,
      chartArea: {width: '90%'},
    };
    var series_col_index = dataTareasTotal.getNumberOfColumns() - 2;
    optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
    optionsTareas.colors = {{ tareas_equipos.total.colores | tojson }}

    var chartTareas = new google.visualization.ComboChart(document.getElementById('chartTareas'));
    chartTareas.draw(dataTareasTotal, optionsTareas);


    // Filtro
    google.visualization.events.addListener(chartDiasEtapas, 'select', selectHandler);
    function selectHandler(e){
      var selection = chartDiasEtapas.getSelection()

      // Identificar filtro
      if (selection ==  '') {
        // Volver a los gráficos originales
        chartDiasEtapas.draw(dataEtapasTotal, optionsEtapas);
        chartDiasEquipos.draw(dataEquiposTotal, optionsEquipos);

        var series_col_index = dataTareasTotal.getNumberOfColumns() - 2;
        optionsTareas.series = {};
        optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
        optionsTareas.colors = {{ tareas_equipos.total.colores | tojson }}
        chartTareas.draw(dataTareasTotal, optionsTareas);

      }
      else {
        var item = selection[0];
        // Filtrar gráficos por Definición
        if (dataEtapasTotal.getValue(item.row, 0) == 'Definición de Alcance del Convenio' ) {
          chartDiasEtapas.draw(dataEtapasDefinicion, optionsEtapas);
          chartDiasEtapas.setSelection([{row: 0}]);
          chartDiasEquipos.draw(dataEquiposDefinicion, optionsEquipos);

          var series_col_index = dataTareasDefinicion.getNumberOfColumns() - 2;
          optionsTareas.series = {};
          optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
          optionsTareas.colors = {{ tareas_equipos.definicion.colores | tojson }}
          chartTareas.draw(dataTareasDefinicion, optionsTareas);
        }
        // Filtrar gráficos por Confección
        else if (dataEtapasTotal.getValue(item.row, 0) == 'Confección de Documento de Convenio') {
          chartDiasEtapas.draw(dataEtapasConfeccion, optionsEtapas);
          chartDiasEtapas.setSelection([{row: 1}]);
          chartDiasEquipos.draw(dataEquiposConfeccion, optionsEquipos);

          var series_col_index = dataTareasConfeccion.getNumberOfColumns() - 2;
          optionsTareas.series = {};
          optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
          optionsTareas.colors = {{ tareas_equipos.confeccion.colores | tojson }}
          chartTareas.draw(dataTareasConfeccion, optionsTareas);
        }
        // Filtrar gráficos por Firmas
        else if (dataEtapasTotal.getValue(item.row, 0) == 'Gestión de Visto Bueno y Firmas') {
          chartDiasEtapas.draw(dataEtapasFirmas, optionsEtapas);
          chartDiasEtapas.setSelection([{row: 2}]);
          chartDiasEquipos.draw(dataEquiposFirmas, optionsEquipos);

          var series_col_index = dataTareasFirmas.getNumberOfColumns() - 2;
          optionsTareas.series = {};
          optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
          optionsTareas.colors = {{ tareas_equipos.firmas.colores | tojson }}
          chartTareas.draw(dataTareasFirmas, optionsTareas);
        }
        // Filtrar gráficos por Resolución
        else if (dataEtapasTotal.getValue(item.row, 0) == 'Generación de Resolución y Protocolo Técnico') {
          chartDiasEtapas.draw(dataEtapasResolucion, optionsEtapas);
          chartDiasEtapas.setSelection([{row: 3}]);
          chartDiasEquipos.draw(dataEquiposResolucion, optionsEquipos);

          var series_col_index = dataTareasResolucion.getNumberOfColumns() - 2;
          optionsTareas.series = {};
          optionsTareas.series[series_col_index] = {type: 'line', pointSize: 6, color:'#2D312A' };
          optionsTareas.colors = {{ tareas_equipos.resolucion.colores | tojson }}
          chartTareas.draw(dataTareasResolucion, optionsTareas);
        }
      }
    }}

</script>



<!-- Listado convenios -->
<script type="text/javascript">
  google.charts.load('current', {'packages':['table']});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var dataTablaListado = new google.visualization.DataTable();
    dataTablaListado.addColumn('string', 'Institución');
    dataTablaListado.addColumn('string', 'Nombre de convenio');
    dataTablaListado.addColumn('string', 'Etapa actual');
    dataTablaListado.addColumn('string', 'Área actual');
    dataTablaListado.addColumn('string', 'Ver res.')

    var dataListado = {{ listado_convenios | tojson }}
    dataTablaListado.addRows(dataListado);
    dataTablaListado.setProperty(0, 0, 'style', 'width: 250px');
    dataTablaListado.setProperty(0, 4, 'style', 'width: 70px');
    dataTablaListado.setProperty(0, 3, 'style', 'width: 150px');
    optionsTablaListado = {
      allowHtml: true,
      width: '100%',
      sortColumn: 0,
    };

    var tablaListado = new google.visualization.Table(document.getElementById('listadoConvenios'));
    tablaListado.draw(dataTablaListado, optionsTablaListado);
  }
</script>


<script type="text/javascript">
  // Ir al detalle del convenio cuando se seleccione uno
  const convenio = document.querySelector('#convenio');
  convenio.addEventListener('change', function(e) {
    //Ir a la página del convenio
    window.location.replace(Flask.url_for('informes.detalle_convenio_en_proceso', {'id_convenio': convenio.value}))
  });

</script>




{% endblock content %}

convenios_app/templates/informes/convenios_por_institucion.html
{% extends 'layout.html' %}
{% block content %}
{{ JSGlue.include() }}
<script src='{{ url_for("static", filename="script.js") }}'></script>
<script type="text/javascript">
  changeActive('#conveniosInstitucion')
</script>
<legend class="border-bottom mb-2">Convenios por Institución <a class="simple-link push-right pe-1" href="{{ url_for('descargas.descargar_informes_institucion') }}"><i class="fa-solid fa-file-excel"></i></a></legend>
<div class="mb-5 overflow-auto">
  <input type="text" class="form-control mb-3" id="searchInstitucion" onkeyup="search()" placeholder="Escriba una institución para filtrar">
  <div id="tablaInstituciones"></div>
</div>

<!-- Modal ver conveios institución -->
<div class="modal" id="institucionModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="modalTitle" class="modal-title"></h5>
        <button type="button" class="btn-modal-exit" data-bs-dismiss="modal" aria-label="Close">
          <i class="fa-solid fa-xmark"></i>
        </button>
      </div>
      <div class="modal-body">
        <div class="mb-5 overflow-auto">
          <div id="detalleInstitucion"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#institucionModal').on('show.bs.modal', function(e) {
    $(this).find('.modal-title').text(e.relatedTarget.text);
  
    // Obtener info de la institución
    const id_institucion = $(e.relatedTarget).data('href');
    fetch(Flask.url_for('informes.obtener_detalle_institucion', {'id_institucion': id_institucion}))
    .then(response => response.json())
    .then(data => {
      // Tabla detalle institución
      google.charts.load('current', {'packages': ['table']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var dataTablaDetalle = new google.visualization.DataTable();
        dataTablaDetalle.addColumn('string', 'Convenio');
        dataTablaDetalle.addColumn('string', 'Estado');
        dataTablaDetalle.addColumn('string', 'Recepción');
        dataTablaDetalle.addColumn('string', 'WebServices');

        dataTablaDetalle.addRows(data);

        optionsTablaDetalle = {
          allowHtml: true,
          width: '100%',
          
        };

        var tablaDetalle = new google.visualization.Table(document.getElementById('detalleInstitucion'));
        tablaDetalle.draw(dataTablaDetalle, optionsTablaInstituciones);
  
      }
    });
  });
</script>

<!-- Search box -->
<script>
  function search() {
  // Declare variables
  var input, filter, tableRows, a, i, txtValue;
  input = document.getElementById('searchInstitucion');
  filter = input.value.toUpperCase();
  tableRows = document.querySelectorAll('tbody > tr');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < tableRows.length; i++) {
    a = tableRows[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      tableRows[i].style.display = "";
    } else {
      tableRows[i].style.display = "none";
    }
  }
}
</script>

<script type="text/javascript">
  google.charts.load('current', {'packages': ['table']});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    // Tabla instituciones
    var dataTablaInstituciones = new google.visualization.DataTable();
    dataTablaInstituciones.addColumn('string', 'Institución');
    dataTablaInstituciones.addColumn('string', 'Convenios');
    dataTablaInstituciones.addColumn('string', 'Adendum');
    dataTablaInstituciones.addColumn('string', 'Por firmar');
    dataTablaInstituciones.addColumn('string', 'Otros');
    dataTablaInstituciones.addColumn('string', 'Recepciones');
    dataTablaInstituciones.addColumn('string', 'WebServices');

    var dataInstituciones = {{ instituciones | tojson }}
    dataTablaInstituciones.addRows(dataInstituciones);

    optionsTablaInstituciones = {
      allowHtml: true,
      width: '100%',
      
    };

    var tablaInstituciones = new google.visualization.Table(document.getElementById('tablaInstituciones'));
    tablaInstituciones.draw(dataTablaInstituciones, optionsTablaInstituciones);
  
  }
</script>


{% endblock content %}