convenios_app/documentos/routes.py
from flask import render_template, request, Blueprint, url_for, redirect, flash, abort, jsonify, send_from_directory
from flask_login import current_user, login_required
from convenios_app.users.utils import admin_only, analista_only
from convenios_app.models import (Institucion, Equipo, Persona, Convenio, SdInvolucrada, BitacoraAnalista,
                                  BitacoraTarea, TrayectoriaEtapa, TrayectoriaEquipo, CatalogoWS, WSConvenio,
                                  RecepcionConvenio, Hito, HitosConvenio)
from convenios_app.bitacoras.forms import (NuevoConvenioForm, EditarConvenioForm, NuevaBitacoraAnalistaForm,
                                           NuevaTareaForm, InfoConvenioForm, ETAPAS, AgregarRecepcionForm,
                                           RegistrarHitoForm, EditarRecepcionForm)
from convenios_app import db
from sqlalchemy import and_, or_
from convenios_app.bitacoras.utils import (actualizar_trayectoria_equipo, actualizar_convenio, obtener_iniciales,
                                           dias_habiles, formato_periodicidad)
from convenios_app.main.utils import generar_nombre_institucion, generar_nombre_convenio, formato_nombre
from datetime import datetime, date

documentos = Blueprint('documentos', __name__)


@documentos.route('/proceso_de_convenio')
def proceso_de_convenio():
    return render_template('documentos/proceso_de_convenio.html')

@documentos.route('/files/<documento>')
def files(documento):
    return send_from_directory(directory='static/files', path=documento)
    
@documentos.route('/catalogo_ws')
def catalogo_ws():
    return 'catalogo'

convenios_app/main/routes.py
import json
from datetime import datetime, date
import time
from pprint import pprint
from itertools import groupby
import win32com.client as win32
import locale
import pythoncom

from flask import render_template, Blueprint, url_for, redirect, flash, jsonify
from flask_login import current_user, login_required
from convenios_app.users.utils import admin_only, analista_only
from sqlalchemy import and_, or_, distinct, func

from convenios_app import db
from convenios_app.main.forms import InstitucionForm, PersonaForm, EditarPersonaForm
from convenios_app.main.utils import generar_nombre_institucion, formato_nombre, generar_nombre_convenio
from convenios_app.models import Ministerio, Institucion, Equipo, Persona, Convenio, TrayectoriaEtapa, RecepcionConvenio
from convenios_app.bitacoras.forms import ETAPAS

main = Blueprint('main', __name__)

# TODO: race condition


@main.route('/')
def home():
    # Datos números
    convenios_firmados = Convenio.query.filter(and_(Convenio.fecha_documento != None,
                                                    or_(Convenio.estado == 'En proceso', Convenio.estado == 'En producción'))).count()
    instituciones_firmantes = db.session.query(func.count(distinct(Convenio.id_institucion))).filter(or_(Convenio.estado == 'En producción', Convenio.estado == 'En proceso')).first()[0]
    count_convenios_por_firmar = Convenio.query.filter(and_(Convenio.estado == 'En proceso', Convenio.fecha_documento == None)).count()
    count_convenios_en_proceso = Convenio.query.filter(Convenio.estado == 'En proceso').count()
    count_convenios_en_produccion = Convenio.query.filter(Convenio.estado == 'En producción').count()
    data = {
        'firmados': convenios_firmados,
        'por_firmar': count_convenios_por_firmar,
        'en_produccion': count_convenios_en_produccion,
        'instituciones': instituciones_firmantes,
        'en_proceso': count_convenios_en_proceso
    }

    # Datos gráfico convenios por etapas
    query_convenios_en_proceso = Convenio.query.filter(Convenio.estado == 'En proceso').all()
    data_etapas = [[ETAPAS[0][1], 0],
                   [ETAPAS[1][1], 0],
                   [ETAPAS[2][1], 0],
                   [ETAPAS[3][1], 0]]

    for convenio in query_convenios_en_proceso:
        etapa_actual = TrayectoriaEtapa.query.filter(
            and_(TrayectoriaEtapa.id_convenio == convenio.id, TrayectoriaEtapa.salida == None)).first()
        if etapa_actual.etapa.etapa == ETAPAS[0][1]:
            data_etapas[0][1] += 1
        elif etapa_actual.etapa.etapa == ETAPAS[1][1]:
            data_etapas[1][1] += 1
        elif etapa_actual.etapa.etapa == ETAPAS[2][1]:
            data_etapas[2][1] += 1
        elif etapa_actual.etapa.etapa == ETAPAS[3][1]:
            data_etapas[3][1] += 1

    # Datos gráfico Convenios firmados último 12 meses
    now = time.localtime()
    meses = [time.localtime(time.mktime((now.tm_year, now.tm_mon - n, 1, 0, 0, 0, 0, 0, 0)))[:2] for n in range(12)]
    ultimos_doce_meses = [date(year=mes[0], month=mes[1], day=1) for mes in meses]
    ultimos_doce_meses.sort()
    query_ultimo_año = Convenio.query.filter(Convenio.fecha_documento >= ultimos_doce_meses[0]).order_by(Convenio.fecha_documento.asc()).all()
    dict_ultimo_año = {datetime.strftime(fecha, "%m-%Y"): [] for fecha in ultimos_doce_meses}

    for convenio in query_ultimo_año:
        dict_ultimo_año[datetime.strftime(convenio.fecha_documento, "%m-%Y")].append(f'{generar_nombre_convenio(convenio)}')

    lista_firmados_mes = {}
    for mes, convenios in dict_ultimo_año.items():
        tooltip = '<ul style="text-align: left;">'
        for convenio in convenios:
            tooltip += f'<li>{convenio}</li>'
        tooltip += '</u>'
        lista_firmados_mes[mes] = tooltip

    data_ultimo_año = [[mes, len(convenios)] for mes, convenios in dict_ultimo_año.items()]
    for i, datos in enumerate(data_ultimo_año):
        if i % 2 > 0:
            datos.append("#E6500A")
        else:
            datos.append('#0064A0')
        datos.append(lista_firmados_mes[datos[0]])
    data_ultimo_año.insert(0, ['Mes', 'Convenios firmados'])

    # Datos gráfico Convenios firmados total
    query_firmados_total = Convenio.query.filter(Convenio.fecha_documento != None).order_by(Convenio.fecha_documento.asc()).all()
    años_firmados = [datetime.strftime(convenio.fecha_documento, "%Y") for convenio in query_firmados_total]
    años_firmados = list(dict.fromkeys(años_firmados))

    dict_firmados_total = {año: [] for año in años_firmados}
    for convenio in query_firmados_total:
        dict_firmados_total[datetime.strftime(convenio.fecha_documento, "%Y")].append(
            f'{generar_nombre_convenio(convenio)}')

    lista_firmados_año = {}
    for año, convenios in dict_firmados_total.items():
        tooltip = '<ul style="text-align: left;">'
        for convenio in convenios:
            tooltip += f'<li>{convenio}</li>'
        tooltip += '</u>'
        lista_firmados_año[año] = tooltip

    data_años_total = [[año, len(convenios)] for año, convenios in dict_firmados_total.items()]
    for i, datos in enumerate(data_años_total):
        if i % 2 > 0:
            datos.append("#E6500A")
        else:
            datos.append('#0064A0')
        datos.append(lista_firmados_año[datos[0]])
    data_años_total.insert(0, ['Año', 'Convenios firmados'])

    return render_template('main/home.html', data=data, data_ultimo_año=data_ultimo_año, data_etapas=data_etapas,
                           data_años_total=data_años_total)


@main.route('/personas', methods=['GET', 'POST'])
@login_required
@analista_only
def ver_persona():
    # Crear select field con personas
    personas = [(persona.id, persona.nombre) for persona in Persona.query.order_by(Persona.nombre.asc()).all()]
    personas.insert(0, (0, 'Seleccione persona para editar'))

    # Crear formulario persona
    instituciones = [(institucion.id, generar_nombre_institucion(institucion)) for institucion in Institucion.query.order_by(Institucion.nombre.asc()).all()]
    instituciones.insert(0, (0, 'Seleccionar'))
    equipos = [(equipo.id, equipo.sigla) for equipo in Equipo.query.order_by(Equipo.sigla.asc()).all()]
    equipos.insert(0, (0, 'Seleccionar'))
    form_persona = PersonaForm()
    form_persona.institucion.choices = instituciones
    form_persona.equipo.choices = equipos

    if form_persona.validate_on_submit():
        if int(form_persona.id_persona.data) == 0:
            # NUEVA PERSONA
            # Crear objeto persona
            nueva_persona = Persona(
                nombre=formato_nombre(form_persona.nombre.data),
                correo=form_persona.correo.data,
                telefono=form_persona.telefono.data,
                cargo=formato_nombre(form_persona.cargo.data),
                area=formato_nombre(form_persona.area.data),
                id_institucion=form_persona.institucion.data,
                id_equipo=form_persona.equipo.data,
            )
            # Agregar a la base de datos
            db.session.add(nueva_persona)
            db.session.commit()
            flash(f'Se ha agregado {nueva_persona.nombre} correctamente.', 'success')
            return redirect(url_for('main.ver_persona'))



    return render_template('main/personas.html', form_persona=form_persona, personas=personas)


@main.route('/editar_persona/<int:id_persona>', methods=['GET', 'POST'])
@login_required
@analista_only
def editar_persona(id_persona):
    # Persona a editar
    persona_seleccionada = Persona.query.get(id_persona)

    # Crear select field con personas
    personas = [(persona.id, persona.nombre) for persona in Persona.query.order_by(Persona.nombre.asc()).all()]
    personas.insert(0, (0, 'Agregar nueva persona'))

    # Crear formulario editar persona
    instituciones = [(institucion.id, generar_nombre_institucion(institucion)) for institucion in Institucion.query.order_by(Institucion.nombre.asc()).all()]
    instituciones.insert(0, (0, 'Seleccionar'))
    equipos = [(equipo.id, equipo.sigla) for equipo in Equipo.query.order_by(Equipo.sigla.asc()).all()]
    equipos.insert(0, (0, 'Seleccionar'))
    form_editar_persona = EditarPersonaForm()
    form_editar_persona.institucion.choices = instituciones
    form_editar_persona.equipo.choices = equipos

    # Datos persona para rellenar el formulario
    info_persona = {
        'id_persona': persona_seleccionada.id,
        'nombre': persona_seleccionada.nombre,
        'correo': persona_seleccionada.correo,
        'telefono': persona_seleccionada.telefono,
        'cargo': persona_seleccionada.cargo,
        'area': persona_seleccionada.area,
        'id_institucion': persona_seleccionada.id_institucion,
        'id_equipo': persona_seleccionada.id_equipo
    }

    if form_editar_persona.validate_on_submit():
        persona_seleccionada.actualizar_persona(form=form_editar_persona)
        flash(f'Se ha editado {persona_seleccionada.nombre} correctamente.', 'success')
        return redirect(url_for('main.editar_persona', id_persona=id_persona))

    return render_template('main/editar_persona.html', form_editar_persona=form_editar_persona,
                            personas=personas, info_persona=info_persona)


@main.route('/info_persona/<int:id>', methods=['GET', 'POST'])
@login_required
@analista_only
def obtener_persona(id):
    # Buscar persona a editar
    query = Persona.query.get(id)
    persona = {
        'id': query.id,
        'nombre': query.nombre,
        'correo': query.correo,
        'telefono': query.telefono,
        'equipo': query.id_equipo,
        'institucion': query.id_institucion,
        'area': query.area,
        'cargo': query.cargo,
    }
    return jsonify(persona)



convenios_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--  CSS Stylesheets-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <!--  Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
    <!--
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  -->

    <!-- Ícono barra de búsqueda -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
    <title>Sistema de Convenios</title>

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>

    <!--Google Charts AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>


<body>
  {{ JSGlue.include() }}
  <!--Main Navigation-->
  <header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar bg-white">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-1">
          <!-- Formularios mostrar solo si el usuario es analista o admin-->
          {% if current_user.is_authenticated %}
            {% if current_user.permisos == 'Admin' or current_user.permisos == 'Analista' %}
              <p class="sidebar-header mb-0 fw-bold fs-6">Formularios</p>
              <a id='bitacoraConvenio' href="{{ url_for('bitacoras.bitacora') }}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                <i class="fa-solid fa-keyboard fa-fw me-3"></i><span>Bitácora</span>
              </a>
              <a id='nuevoConvenio' href="{{ url_for('bitacoras.agregar_convenio') }}" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fa-solid fa-folder-plus fa-fw me-3"></i><span>Convenio</span>
              </a>
              <a id='instituciones' href="{{ url_for('main.ver_institucion') }}" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fa-solid fa-landmark fa-fw me-3"></i><span>Instituciones</span>
              </a>
              <a id='personas' href="{{ url_for('main.ver_persona') }}" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-user fa-fw me-3"></i><span>Personas</span>
              </a>
              <a id='bitacoraMapas' href="{{ url_for('bitacoras.bitacora_mapas') }}" class="list-group-item list-group-item-action py-2 ripple mb-4">
                <i class="fa-solid fa-map fa-fw me-3"></i><span>Mapas</span>
              </a>
            {% endif %}
          {% endif %}
          <!-- Informes -->
          <p class="sidebar-header mb-0 fw-bold">Informes<i class="fas fa-search btn-sm"></i></p>
          <a id='conveniosProceso' href="{{ url_for('informes.convenios_en_proceso') }}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
            <i class="fa-solid fa-folder-open fa-fw me-3"></i><span>C. en proceso</span>
          </a>
          <a id='conveniosProduccion' href="{{ url_for('informes.convenios_en_produccion') }}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fa-solid fa-folder-tree fa-fw me-3"></i><span>C. en producción</span>
          </a>
          <a id='otrosConvenios' href="{{ url_for('informes.otros_convenios') }}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fa-solid fa-dumpster fa-fw me-3"></i><span>Otros convenios</span>
          </a>
          <a id='conveniosInstitucion' href="{{ url_for('informes.convenios_por_institucion') }}" class="list-group-item list-group-item-action py-2 ripple mb-4">
            <i class="fa-solid fa-building-columns me-3"></i><span>C. por institución</span>
          </a>
        <!--  <a href="#" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-file-alt fa-fw me-3"></i><span>Recepción</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fa-solid fa-folder-tree fa-fw me-3"></i><span>Entrega</span></span>
          </a> -->

          <!-- Documentos -->
          <p class="sidebar-header mb-0 fw-bold">Documentos</p>
          <a id='procesoConvenio' href="{{ url_for('documentos.proceso_de_convenio') }}" class="list-group-item list-group-item-action py-2 ripple mb-4" aria-current="true">
            <i class="fa-solid fa-file-invoice fa-fw me-3"></i><span>Proceso de C.</span>
          </a>
          <!--
          <a id='catalogoWS' href="{{ url_for('documentos.catalogo_ws') }}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fa-solid fa-file-lines fa-fw me-3"></i><span>Catálogo de WS</span>
          </a>
          -->
          <!-- Intercambio de información-->

          <p class="sidebar-header mb-0 fw-bold fs-6">Intercambio información</p>
          <a id='entregasGE' href="{{ url_for('intercambio.entregas_ge') }}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-arrow-right-arrow-left fa-fw me-3"></i><span>Entregas GE</span>
          </a>     
              <a id='recepcionSFTP' href="{{ url_for('intercambio.recepcion_sftp') }}" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-arrow-right-arrow-left fa-fw me-3"></i><span>Recepción SFTP</span>
              </a>

        </div>
      </div>
    </nav>
    <!-- Sidebar -->

    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-primary fixed-top pl-0">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <!-- Brand -->
        <div class="navbar-brand">
          <a href="{{ url_for('main.home') }}" id='brand-link'>Sistema de Convenios</a>
        </div>

        <!-- Buscador -->
        {% if current_user.is_authenticated %}
          {% if current_user.permisos == 'Admin' or current_user.permisos == 'Analista' %}
            <div class="ps-4" style='width:600px;'>
              <select class="form-control form-control-sm form-select" id="selectNavBar">
                <option value="0">Seleccione convenio para ver bitácora</option>
              </select>
            </div> 
          {% endif %}
        {% endif %}
      
        <!-- Right links -->
        <div class="navbar-nav ms-auto d-flex flex-row">
            {% if current_user.is_authenticated %}
              {% if current_user.permisos == 'Admin' or current_user.permisos == 'Subdirección' %}
                <a class="nav-item nav-link" href="{{ url_for('users.convenios_sd', id_persona=current_user.id_persona) }}">Convenios SD</a>
              {% endif %}
              {% if current_user.permisos == 'Admin' or current_user.permisos == 'Analista' %}
                <a class="nav-item nav-link" href="{{ url_for('users.mis_convenios', id_persona=current_user.id_persona) }}">Mis convenios</a>
              {% endif %}
              {% if current_user.permisos == 'Admin' %}
                <a class="nav-item nav-link" href="{{ url_for('users.registrar_usuario') }}">Registrar</a>
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('users.salir') }}">Salir</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.ingresar') }}">Ingresar</a>
            {% endif %}

        </div>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->

  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class='alert alert-{{category}} alert-dismissible text-center fade show'>
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}
      {% endblock content %}
    </div>
  </main>
  <!--Main layout-->

  <!-- Footer Layout -->


  <!-- JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  <script>
    
    $(document).ready(function(){
      // Completar el select con todos los convenios
      var selectBar = $('#selectNavBar');
      fetch(Flask.url_for('main.obtener_convenios_todos'))
      .then(response => response.json())
      .then(data => {
        $.each(data, function(convenio, id){
          selectBar.append(new Option(convenio, id));
        });
      });

      // Ir a la página de convenio cuando se seleccione en el buscador
      $('#selectNavBar').change(function(){
      var id = $(this).find(":selected").val();
      window.location.replace(Flask.url_for('bitacoras.bitacora_convenio', {'id_convenio': id}));
    });

    });
  </script>

</body>
</html>