convenios_app/documentos/routes.py
from flask import render_template, request, Blueprint, url_for, redirect, flash, abort, jsonify, send_from_directory
from flask_login import current_user, login_required
from convenios_app.users.utils import admin_only, analista_only
from convenios_app.models import (Institucion, Equipo, Persona, Convenio, SdInvolucrada, BitacoraAnalista,
                                  BitacoraTarea, TrayectoriaEtapa, TrayectoriaEquipo, CatalogoWS, WSConvenio,
                                  RecepcionConvenio, Hito, HitosConvenio)
from convenios_app.bitacoras.forms import (NuevoConvenioForm, EditarConvenioForm, NuevaBitacoraAnalistaForm,
                                           NuevaTareaForm, InfoConvenioForm, ETAPAS, AgregarRecepcionForm,
                                           RegistrarHitoForm, EditarRecepcionForm)
from convenios_app import db
from sqlalchemy import and_, or_
from convenios_app.bitacoras.utils import (actualizar_trayectoria_equipo, actualizar_convenio, obtener_iniciales,
                                           dias_habiles, formato_periodicidad)
from convenios_app.main.utils import generar_nombre_institucion, generar_nombre_convenio, formato_nombre
from datetime import datetime, date

documentos = Blueprint('documentos', __name__)


@documentos.route('/proceso_de_convenio')
def proceso_de_convenio():
    return render_template('documentos/proceso_de_convenio.html')

@documentos.route('/files/<documento>')
def files(documento):
    return send_from_directory(directory='static/files', path=documento)
    
@documentos.route('/catalogo_ws')
def catalogo_ws():
    return 'catalogo'

convenios_app/templates/documentos/proceso_de_convenio.html
{% extends 'layout.html' %}
{% block content %}
{{ JSGlue.include() }}
<script src='{{ url_for("static", filename="script.js") }}'></script>
<script type="text/javascript">
  changeActive('#procesoConvenio')
</script>

<div class="content-section mx-4">
    <legend class="border-bottom mb-3">Proceso de Convenio</legend>
    <img class="mx-auto d-block" src="{{ url_for('static', filename='flujo_general.png') }}">
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='documento_descriptivo_del_proceso_de_convenio.pdf') }}">
      Descriptivo
    </a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="http://intranet_sii/administra/ocircu/2022/ocircu5.pdf">
      Oficio Circular N°05 del 07 de marzo de 2022</a></p>
    <p><a class="simple-link" target="_blank" href="http://intranet_sii/ins_mat_consulta/gestionProceso/normativa_proceso_convenio_intercambio_Informacion.pdf">
      Normativa del proceso</a></p>    

    <h5 class="mt-4">I. Elaboración y Firma de Convenio</h5>
    <img class="mx-auto d-block" src="{{ url_for('static', filename='elaboracion_y_firma.png') }}">
    <h6 class="mb-0">Definición de Alcance del Convenio</h6>
    <p class='mb-0'><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_definicion_de_alcance_del_convenio.pdf') }}">
      Flujo etapa</a></p>
    <p class='mb-0'><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='procedimiento_reunion_de_kickoff.pdf') }}">
      Procedimiento - Reunión de Kickoff</a></p>
    <p class='mb-0'><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='acta_de_convenio_reunion_de_kickoff.pdf') }}">
      Acta de Convenio - Reunión de Kickoff</a></p>
    <p class='mb-0'><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='procedimiento_reunion_de_alcance_de_convenio.pdf') }}">
      Procedimiento - Reunión de Alcance de Convenio</a></p>
    <p class='mb-3'><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='ficha_de_convenio_reunion_de_alcance_de_convenio.pdf') }}">
      Ficha de Convenio - Reunión de Alcance de Convenio</a></p>
   
    <h6 class="mb-0">Confección de Documento de Convenio</h6>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_confeccion_de_documento_de_convenio.pdf') }}">
      Flujo etapa</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='convenio_tipo.pdf') }}">
      Convenio tipo</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='convenio_clave_tributaria_tipo.pdf') }}">
      Convenio Clave Tributaria tipo</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='procedimiento_reunion_sancionatoria_de_convenio.pdf') }}">
      Procedimiento - Reunión Sancionatoria de Convenio</a></p>
    <p class="mb-3"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='acta_de_acuerdo_reunion_sancionatoria_de_convenio.pdf') }}">
      Acta de Acuerdo - Reunión Sancionatoria de Convenio</a></p> 
    
    <h6 class="mb-0">Gestión de Visto Bueno y Firmas</h6>
    <p class="mb-3"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_gestion_de_visto_bueno_y_firmas.pdf') }}">
      Flujo etapa</a></p> 

    <h6 class="mb-0">Generación de Resolución y Protocolo Técnico</h6>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_generacion_de_resolucion_y_visto_bueno.pdf') }}">
      Flujo etapa</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='resolucion_tipo.pdf') }}">
      Resolución tipo</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='ficha_publicacion_tipo.xlsm') }}">
      Ficha publicación Gabinete del Director</a></p>
    <p class="mb-0"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='protocolo_tecnico_tipo.pdf') }}">
      Protocolo Técnico tipo</a></p>

    <h5>II. Implementación y Disponibilidad de los Convenios</h5>
    <img class="mx-auto d-block" src="{{ url_for('static', filename='implementacion_y_monitoreo.PNG') }}">
    <h6 class="mb-0">Implementación de los Convenios</h6>
    <p class="mb-3"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_implementacion_de_los_convenios.pdf') }}">
      Flujo etapa</a></p> 
    <h6 class="mb-0">Monitoreo y Gestión para la Disponibilidad de Datos</h6>
    <p class="mb-3"><a class="simple-link" target="_blank" href="{{ url_for('documentos.files', documento='flujo_monitoreo_y_gestion_para_la_disponibilidad_de_datos.pdf') }}">
      Flujo etapa</a></p> 
</div>
{% endblock content %}